package com.idm4j.boot.app.data.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", catalog = "auth_service")
public class Profile implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String password;
	private String status;
	private Date createdDate;
	private Date lastUpdated;
	private Date lastRequestFailedDate;
	private Integer failedAttempt;

	public Profile() {
	}

	public Profile(String userId, String password, String status, Date createdDate, Date lastUpdated,
			Date lastRequestFailedDate, Integer failedAttempt) {
		this.userId = userId;
		this.password = password;
		this.status = status;
		this.createdDate = createdDate;
		this.lastUpdated = lastUpdated;
		this.lastRequestFailedDate = lastRequestFailedDate;
		this.failedAttempt = failedAttempt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated", length = 10)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_request_failed_date", length = 10)
	public Date getLastRequestFailedDate() {
		return this.lastRequestFailedDate;
	}

	public void setLastRequestFailedDate(Date lastRequestFailedDate) {
		this.lastRequestFailedDate = lastRequestFailedDate;
	}

	@Column(name = "failed_attempt")
	public Integer getFailedAttempt() {
		return this.failedAttempt;
	}

	public void setFailedAttempt(Integer failedAttempt) {
		this.failedAttempt = failedAttempt;
	}

}
